name: Build and Deploy

on:
  push:
    branches:
      - master  # Adjust if your default branch is named differently, like 'main'

jobs:
  build_and_deploy:
    runs-on: self-hosted  # Ensure this matches the label for your self-hosted runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Maven and Java environment
      run: |
        echo "JAVA_HOME=${JAVA_HOME}"
        java -version
        mvn -version

    - name: Build with Maven
      run: |
        cd app-repo/Application-repo-AutoD  # Ensure this directory is correct
        mvn -f ./pom.xml clean package

    - name: Build Docker image
      run: sudo docker build -t petad .

    - name: Run Docker container
      run: sudo docker run -d -p 8085:8085 petad
